version: '3'
volumes:
  dados:
networks:
  banco-de-dados:
  web:
services:
  db:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=123456
    volumes:
      # Volume dos dados
      - dados:/var/lib/postgresql/data
      # Scripts
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - banco-de-dados
    ports:
      - 5432:5432
  frontend:
    image: nginx:1.13
    volumes:
      - ./frontend:/usr/share/nginx/html/
    ports:
      - 80:80
    networks:
      - web
    depends_on:
      - backend
  backend:
    image: node:8.1
    volumes: 
      - ./backend:/backend
    working_dir: /backend
    ports:
      - 8080:8080
    command: bash -c "cd /backend && npm i && npm start"
    networks:
      - web
      - banco-de-dados
    depends_on:
      - db