version: '3'
volumes:
  dados:
services:
  db:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=123456
    volumes:
      # Volume dos dados
      - dados:/var/lib/postgresql/data
      # Scripts
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
  frontend:
    image: nginx:1.13
    volumes:
      - ./frontend:/usr/share/nginx/html/
    ports:
      - 80:80
  backend:
    image: node:8.1
    volumes: 
      - ./backend:/backend
    ports:
      - 8080:8080
    command: bash -c "cd /backend && npm i && npm start"