version: '3'
volumes:
  dados:
services:
  db:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=123456
    volumes:
      # Volume dos dados
      - dados:/var/lib/postgresql/data
      # Scripts
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql